query getProducts(
  $where: ProductWhereInput,
  $first: Int,
  $last: Int,
  $skip: Int,
  $orderBy: ProductOrderByInput
) {
  products(
    where: $where,
    first: $first,
    last: $last,
    skip: $skip,
    orderBy: $orderBy
  ) {
    id
    name
    slug
    price
    featured
    description
    bestseller
    category

    image {
      size
      url
      width
      height
    }

    recommendations {
      slug
    	image {
        size
        url
        width
        height
      }
    }
  }
}
