query getProducts($where: ProductWhereInput, $first: Int, $last: Int, $skip: Int) {
  products(where: $where, first: $first, last: $last, skip: $skip) {
    id
    name
    slug
    price
    featured
    description
    bestseller
    category

    image {
      size
      url
      width
      height
    }

    recommendations {
      slug
    	image {
        size
        url
        width
        height
      }
    }
  }
}
